{{- if and .Values.vals.enabled .Values.vals.configRef }}
apiVersion: digitalis.io/v1
kind: ValsSecret
metadata:
<<<<<<< HEAD
  name: {{ include "axon-server.fullname" . }}
=======
  name: {{ include "axon-server.fullname" . }}-vals
>>>>>>> origin/development
  labels:
    {{- include "axon-server.labels" . | nindent 4 }}
    {{- with .Values.vals.labels }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
  {{- with .Values.vals.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
<<<<<<< HEAD
  name: {{ include "axon-server.fullname" . }}
=======
  name: {{ include "axon-server.fullname" . }}-vals
>>>>>>> origin/development
  ttl: {{ .Values.vals.ttl | default 3600 }}
  data:
    axon-server.yml:
      ref: {{ .Values.vals.configRef | quote }}
{{- end }}
